### ISSUE TITLE
Dispose of messages client-side after timer expires

### ISSUE THREAD

**Issue by suve** [chris13524/privatepm#13]
When a message expires, it is not disposed of client-side, and thus can be kept indefinitely.

The client already has code for checking the message expiry time and comparing it to current time, but this is only used to update the "this message will self-destruct in XXX days" message.

---
![one-day-ago](https://user-images.githubusercontent.com/5345765/103759541-2f6a5d80-5014-11eb-943c-328c1678c84d.png)

**Comment by chris13524** [comment]
Hi @suve thank you for the issue!

Disposing of messages is already done [here](https://github.com/chris13524/privatepm/blob/master/client/src/app/main/display/display.component.ts#L89). You should be able to see this in action if you set the expiration to 15 seconds.
